# Generated by Django 4.0.4 on 2022-05-15 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default=None, null=True, verbose_name='code')),
                ('min_purchase', models.IntegerField(default=None, null=True, verbose_name='Achat minimum')),
                ('max_purchase', models.IntegerField(default=None, null=True, verbose_name='Achat maximal')),
                ('deadline', models.DateTimeField(default=None, null=True, verbose_name="Date d'expiration")),
                ('unit', models.CharField(choices=[('percent', '%'), ('integer', 'nombre')], default=None, max_length=255, null=True, verbose_name="Unité d'expression")),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de modification')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Date de suppression')),
                ('client', models.ManyToManyField(related_name='DiscountCode_clients', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
        ),
    ]
