# Generated by Django 4.0.4 on 2022-05-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_requests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='discountcodes',
            options={'verbose_name': 'Code Promo'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Commande'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Paiement'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Requête'},
        ),
        migrations.AlterField(
            model_name='profiles',
            name='contact',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Contact'),
        ),
    ]
