# Generated by Django 4.0.4 on 2022-05-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_categories_options_alter_discountcodes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='birth_date',
            field=models.DateField(default=None, null=True, verbose_name='Date de naissance'),
        ),
    ]
