# Generated by Django 4.0.4 on 2022-06-10 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0015_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Store_User', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
    ]
