# Generated by Django 4.0.4 on 2022-06-10 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0016_store_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Stores',
        ),
    ]
