# Generated by Django 4.0.4 on 2022-06-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_stores_created_at_stores_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='store_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='store_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='store_status',
            new_name='status',
        ),
    ]
