# Generated by Django 4.0.4 on 2022-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_categories_name_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de suppression'),
        ),
    ]
