# Generated by Django 4.0.4 on 2022-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_discountcodes_seller_alter_messages_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ManyToManyField(related_name='Products_sub_Categories', to='website.subcategories', verbose_name='Sous Catégorie'),
        ),
    ]
