# Generated by Django 4.0.4 on 2022-06-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_products_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='Products_sub_Categories', to='website.subcategories', verbose_name='Sous Catégorie'),
        ),
    ]
