# Generated by Django 4.0.4 on 2022-06-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_products_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stores',
            options={'verbose_name': 'Store'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Nom de la boutique'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='Nom'),
        ),
    ]
